version: "3"

volumes:
  cartable_local_postgres_data: {}

services:
  cartable: &cartable
    build:
      context: .
      dockerfile: ./compose/local/cartable/Dockerfile
    image: cartable
    container_name: cartable
    depends_on:
      - cartable_db
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.cartable
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  cartable_db:
    image: postgres:14
    container_name: cartable_db
    ports:
      - "5432:5432"
    volumes:
      - cartable_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
