# Generated by Django 5.1 on 2024-09-05 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_statuses', to='service.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'Request Status',
                'verbose_name_plural': 'Request Statuses',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='reacking code')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('viewed_by_admin', models.BooleanField(default=False, verbose_name='viewed by admin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='service.service', verbose_name='service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='service.servicestatus', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
